spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/swapnilhota/microservices.project2.configurations
          clone-on-start: true

server:
  port: 8888